/**
 * ============================================================
 * AURA REALTY — Property Data Store
 * ============================================================
 * Contains all dummy property listings used throughout the site.
 * Each property includes: location data, pricing, features,
 * agent info, images, and map coordinates.
 * 
 * To integrate a real backend later, replace this file with
 * API calls that return data in the same shape.
 * ============================================================
 */

const PROPERTIES = [
  {
    id: 1,
    title: "Modern Luxury Villa",
    price: 1250000,
    address: "1234 Oceanview Dr",
    city: "Miami",
    state: "FL",
    zip: "33139",
    lat: 25.7617,
    lng: -80.1918,
    beds: 5,
    baths: 4,
    sqft: 4200,
    type: "House",
    yearBuilt: 2021,
    status: "For Sale",
    featured: true,
    description: "Stunning modern villa with panoramic ocean views, infinity pool, gourmet kitchen with top-of-the-line appliances, and a spacious open floor plan. Smart home technology throughout. Located in the prestigious Miami Beach neighborhood.",
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop"],
    agent: { name: "Sarah Mitchell", phone: "(305) 555-0101", email: "sarah@aurarealty.com", photo: "" }
  },
  {
    id: 2,
    title: "Downtown Penthouse Suite",
    price: 2100000,
    address: "500 Brickell Ave #PH1",
    city: "Miami",
    state: "FL",
    zip: "33131",
    lat: 25.7650,
    lng: -80.1890,
    beds: 3,
    baths: 3,
    sqft: 3100,
    type: "Condo",
    yearBuilt: 2023,
    status: "For Sale",
    featured: true,
    description: "Exclusive penthouse suite in the heart of Brickell. Floor-to-ceiling windows offer breathtaking city and bay views. Features include a private elevator, chef's kitchen, marble finishes, and resort-style amenities.",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop"],
    agent: { name: "Michael Chen", phone: "(305) 555-0102", email: "michael@aurarealty.com", photo: "" }
  },
  {
    id: 3,
    title: "Charming Colonial Home",
    price: 675000,
    address: "78 Maple Street",
    city: "Greenwich",
    state: "CT",
    zip: "06830",
    lat: 41.0262,
    lng: -73.6282,
    beds: 4,
    baths: 3,
    sqft: 2800,
    type: "House",
    yearBuilt: 1998,
    status: "For Sale",
    featured: true,
    description: "Beautiful colonial home on a quiet tree-lined street. Features hardwood floors, a fireplace, updated kitchen and bathrooms, and a large backyard perfect for entertaining. Close to top-rated schools and downtown shopping.",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop"],
    agent: { name: "Emily Rodriguez", phone: "(203) 555-0103", email: "emily@aurarealty.com", photo: "" }
  },
  {
    id: 4,
    title: "Sleek City Apartment",
    price: 425000,
    address: "200 W 72nd St #14B",
    city: "New York",
    state: "NY",
    zip: "10023",
    lat: 40.7769,
    lng: -73.9813,
    beds: 2,
    baths: 1,
    sqft: 1100,
    type: "Apartment",
    yearBuilt: 2019,
    status: "For Sale",
    featured: false,
    description: "Contemporary apartment in the Upper West Side with an open layout, modern finishes, in-unit laundry, and building amenities including a fitness center, rooftop lounge, and doorman service.",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop"],
    agent: { name: "David Park", phone: "(212) 555-0104", email: "david@aurarealty.com", photo: "" }
  },
  {
    id: 5,
    title: "Lakefront Estate",
    price: 1875000,
    address: "450 Lakeshore Blvd",
    city: "Lake Tahoe",
    state: "CA",
    zip: "96150",
    lat: 38.9399,
    lng: -119.9772,
    beds: 6,
    baths: 5,
    sqft: 5500,
    type: "House",
    yearBuilt: 2020,
    status: "For Sale",
    featured: true,
    description: "Magnificent lakefront estate with private dock and stunning mountain views. Features include a gourmet kitchen, home theater, wine cellar, heated floors, and expansive deck overlooking Lake Tahoe.",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop"],
    agent: { name: "Sarah Mitchell", phone: "(305) 555-0101", email: "sarah@aurarealty.com", photo: "" }
  },
  {
    id: 6,
    title: "Urban Loft Living",
    price: 550000,
    address: "88 Arts District Way #3A",
    city: "Los Angeles",
    state: "CA",
    zip: "90013",
    lat: 34.0407,
    lng: -118.2352,
    beds: 2,
    baths: 2,
    sqft: 1650,
    type: "Condo",
    yearBuilt: 2022,
    status: "For Sale",
    featured: false,
    description: "Industrial-chic loft in the vibrant Arts District. Soaring 16-foot ceilings, exposed brick, polished concrete floors, and an open floor plan. Walking distance to galleries, restaurants, and nightlife.",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop"],
    agent: { name: "Jessica Taylor", phone: "(213) 555-0106", email: "jessica@aurarealty.com", photo: "" }
  },
  {
    id: 7,
    title: "Suburban Family Home",
    price: 485000,
    address: "321 Oak Ridge Lane",
    city: "Austin",
    state: "TX",
    zip: "78759",
    lat: 30.4000,
    lng: -97.7500,
    beds: 4,
    baths: 3,
    sqft: 2400,
    type: "House",
    yearBuilt: 2018,
    status: "For Sale",
    featured: false,
    description: "Spacious family home in a sought-after Austin neighborhood. Open concept living, granite countertops, stainless steel appliances, covered patio, and a two-car garage. Community pool and playground nearby.",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop"],
    agent: { name: "Michael Chen", phone: "(305) 555-0102", email: "michael@aurarealty.com", photo: "" }
  },
  {
    id: 8,
    title: "Beachfront Paradise",
    price: 3200000,
    address: "1 Ocean Front Walk",
    city: "Malibu",
    state: "CA",
    zip: "90265",
    lat: 34.0259,
    lng: -118.7798,
    beds: 5,
    baths: 4,
    sqft: 4800,
    type: "House",
    yearBuilt: 2022,
    status: "For Sale",
    featured: true,
    description: "Exquisite beachfront property with direct sand access. Floor-to-ceiling glass walls, outdoor living areas, infinity edge pool, and a private path to the beach. Every room designed to capture stunning Pacific Ocean views.",
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop"],
    agent: { name: "Emily Rodriguez", phone: "(203) 555-0103", email: "emily@aurarealty.com", photo: "" }
  },
  {
    id: 9,
    title: "Historic Brownstone",
    price: 1450000,
    address: "156 Commonwealth Ave",
    city: "Boston",
    state: "MA",
    zip: "02116",
    lat: 42.3510,
    lng: -71.0735,
    beds: 4,
    baths: 3,
    sqft: 3200,
    type: "Townhouse",
    yearBuilt: 1895,
    status: "For Sale",
    featured: false,
    description: "Meticulously restored Back Bay brownstone combining period details with modern upgrades. Original moldings, fireplaces, and hardwood floors complemented by a chef's kitchen, central air, and a private roof deck.",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop"],
    agent: { name: "David Park", phone: "(212) 555-0104", email: "david@aurarealty.com", photo: "" }
  },
  {
    id: 10,
    title: "Mountain Retreat Cabin",
    price: 389000,
    address: "900 Pineview Trail",
    city: "Aspen",
    state: "CO",
    zip: "81611",
    lat: 39.1911,
    lng: -106.8175,
    beds: 3,
    baths: 2,
    sqft: 1800,
    type: "House",
    yearBuilt: 2017,
    status: "For Sale",
    featured: false,
    description: "Cozy mountain cabin with stunning views. Vaulted ceilings with exposed beams, stone fireplace, wraparound deck, and a hot tub. Perfect year-round retreat for skiing, hiking, and mountain living.",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop"],
    agent: { name: "Jessica Taylor", phone: "(213) 555-0106", email: "jessica@aurarealty.com", photo: "" }
  },
  {
    id: 11,
    title: "Luxury High-Rise Condo",
    price: 890000,
    address: "1000 Michigan Ave #42F",
    city: "Chicago",
    state: "IL",
    zip: "60611",
    lat: 41.8827,
    lng: -87.6233,
    beds: 3,
    baths: 2,
    sqft: 2200,
    type: "Condo",
    yearBuilt: 2021,
    status: "For Sale",
    featured: true,
    description: "Stunning high-rise condo with panoramic views of Lake Michigan and the Chicago skyline. Premium finishes include custom cabinetry, quartz counters, and hardwood floors. Full-service building with pool, spa, and concierge.",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop"],
    agent: { name: "Sarah Mitchell", phone: "(305) 555-0101", email: "sarah@aurarealty.com", photo: "" }
  },
  {
    id: 12,
    title: "Cozy Studio Apartment",
    price: 215000,
    address: "55 Pine St #7C",
    city: "Seattle",
    state: "WA",
    zip: "98101",
    lat: 47.6062,
    lng: -122.3321,
    beds: 1,
    baths: 1,
    sqft: 650,
    type: "Apartment",
    yearBuilt: 2020,
    status: "For Sale",
    featured: false,
    description: "Efficient and stylish studio in downtown Seattle. Features include a Murphy bed, built-in storage, modern kitchen, and in-unit washer/dryer. Steps from Pike Place Market and the waterfront.",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop"],
    agent: { name: "Michael Chen", phone: "(305) 555-0102", email: "michael@aurarealty.com", photo: "" }
  },
  {
    id: 13,
    title: "Spanish Revival Estate",
    price: 1650000,
    address: "2200 Sunset Blvd",
    city: "Beverly Hills",
    state: "CA",
    zip: "90210",
    lat: 34.0901,
    lng: -118.4065,
    beds: 5,
    baths: 4,
    sqft: 4100,
    type: "House",
    yearBuilt: 1935,
    status: "For Sale",
    featured: false,
    description: "Iconic Spanish Revival estate in Beverly Hills. Arched doorways, terracotta tile, lush courtyard gardens, and a sparkling pool. Thoughtfully renovated to preserve original character while adding modern luxury.",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop"],
    agent: { name: "Jessica Taylor", phone: "(213) 555-0106", email: "jessica@aurarealty.com", photo: "" }
  },
  {
    id: 14,
    title: "Waterfront Townhouse",
    price: 725000,
    address: "42 Harbor View Ct",
    city: "San Diego",
    state: "CA",
    zip: "92101",
    lat: 32.7157,
    lng: -117.1611,
    beds: 3,
    baths: 3,
    sqft: 2100,
    type: "Townhouse",
    yearBuilt: 2019,
    status: "For Sale",
    featured: false,
    description: "Contemporary waterfront townhouse with rooftop terrace and harbor views. Open living areas, gourmet kitchen, attached two-car garage, and private patio. Walk to restaurants, shops, and the Gaslamp Quarter.",
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop"],
    agent: { name: "Emily Rodriguez", phone: "(203) 555-0103", email: "emily@aurarealty.com", photo: "" }
  },
  {
    id: 15,
    title: "Modern Farmhouse",
    price: 560000,
    address: "800 Country Club Rd",
    city: "Nashville",
    state: "TN",
    zip: "37215",
    lat: 36.1037,
    lng: -86.8118,
    beds: 4,
    baths: 3,
    sqft: 3000,
    type: "House",
    yearBuilt: 2023,
    status: "For Sale",
    featured: false,
    description: "New construction modern farmhouse with shiplap accents, barn doors, and a wraparound porch. Chef's kitchen with farmhouse sink, mudroom, and a finished bonus room. Located in a charming Nashville neighborhood.",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop"],
    agent: { name: "David Park", phone: "(212) 555-0104", email: "david@aurarealty.com", photo: "" }
  },
  {
    id: 16,
    title: "Luxury Penthouse Loft",
    price: 1975000,
    address: "75 Wall St #PH2",
    city: "New York",
    state: "NY",
    zip: "10005",
    lat: 40.7074,
    lng: -74.0090,
    beds: 3,
    baths: 3,
    sqft: 2800,
    type: "Condo",
    yearBuilt: 2024,
    status: "For Sale",
    featured: true,
    description: "Ultra-luxury penthouse loft in the Financial District. Double-height ceilings, private terrace with city views, spa-like bathrooms, and Boffi kitchen. Full-service building with pool, gym, and 24-hour concierge.",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop"],
    agent: { name: "Sarah Mitchell", phone: "(305) 555-0101", email: "sarah@aurarealty.com", photo: "" }
  },
  {
    id: 17,
    title: "Desert Oasis Home",
    price: 445000,
    address: "1500 Cactus Flower Dr",
    city: "Scottsdale",
    state: "AZ",
    zip: "85255",
    lat: 33.6940,
    lng: -111.8500,
    beds: 3,
    baths: 2,
    sqft: 2000,
    type: "House",
    yearBuilt: 2020,
    status: "For Sale",
    featured: false,
    description: "Beautiful desert-modern home with mountain views. Features include a resort-style pool, outdoor kitchen, natural stone accents, and energy-efficient design. Enjoy year-round sunshine in Scottsdale's premier community.",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop"],
    agent: { name: "Emily Rodriguez", phone: "(203) 555-0103", email: "emily@aurarealty.com", photo: "" }
  },
  {
    id: 18,
    title: "Chic Studio Loft",
    price: 299000,
    address: "120 Pearl St #5A",
    city: "Portland",
    state: "OR",
    zip: "97209",
    lat: 45.5285,
    lng: -122.6809,
    beds: 1,
    baths: 1,
    sqft: 750,
    type: "Apartment",
    yearBuilt: 2021,
    status: "For Sale",
    featured: false,
    description: "Trendy Pearl District loft with exposed brick, oversized windows, and bamboo flooring. Building features include a courtyard, bike storage, and EV charging. Walk score of 98 — everything you need is at your doorstep.",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop"],
    agent: { name: "Jessica Taylor", phone: "(213) 555-0106", email: "jessica@aurarealty.com", photo: "" }
  },
  {
    id: 19,
    title: "Elegant Georgian Mansion",
    price: 4500000,
    address: "1 Embassy Row",
    city: "Washington",
    state: "DC",
    zip: "20008",
    lat: 38.9160,
    lng: -77.0569,
    beds: 7,
    baths: 6,
    sqft: 8200,
    type: "House",
    yearBuilt: 1920,
    status: "For Sale",
    featured: true,
    description: "Magnificent Georgian mansion on Embassy Row. Grand foyer, ballroom, library, wine cellar, staff quarters, and manicured gardens. A once-in-a-generation opportunity to own a piece of Washington's architectural history.",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop"],
    agent: { name: "Michael Chen", phone: "(305) 555-0102", email: "michael@aurarealty.com", photo: "" }
  },
  {
    id: 20,
    title: "Tropical Garden Villa",
    price: 825000,
    address: "99 Hibiscus Lane",
    city: "Honolulu",
    state: "HI",
    zip: "96815",
    lat: 21.2769,
    lng: -157.8268,
    beds: 3,
    baths: 2,
    sqft: 1900,
    type: "House",
    yearBuilt: 2022,
    status: "For Sale",
    featured: false,
    description: "Tropical paradise with lush garden surroundings and ocean breezes. Indoor-outdoor living with lanai, plunge pool, and outdoor shower. Modern Hawaiian style with natural materials and island-inspired design.",
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop"],
    agent: { name: "David Park", phone: "(212) 555-0104", email: "david@aurarealty.com", photo: "" }
  },
  {
    id: 21,
    title: "Contemporary Glass House",
    price: 2350000,
    address: "777 Skyline Dr",
    city: "San Francisco",
    state: "CA",
    zip: "94114",
    lat: 37.7599,
    lng: -122.4331,
    beds: 4,
    baths: 4,
    sqft: 3500,
    type: "House",
    yearBuilt: 2024,
    status: "For Sale",
    featured: false,
    description: "Architectural masterpiece featuring walls of glass and panoramic city views. Cantilevered design, smart home automation, geothermal heating, and a green roof. A true statement home for the most discerning buyer.",
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&h=600&fit=crop"],
    agent: { name: "Sarah Mitchell", phone: "(305) 555-0101", email: "sarah@aurarealty.com", photo: "" }
  },
  {
    id: 22,
    title: "Renovated Craftsman Bungalow",
    price: 375000,
    address: "456 Elm Street",
    city: "Atlanta",
    state: "GA",
    zip: "30307",
    lat: 33.7629,
    lng: -84.3464,
    beds: 3,
    baths: 2,
    sqft: 1600,
    type: "House",
    yearBuilt: 1940,
    status: "For Sale",
    featured: false,
    description: "Beautifully renovated craftsman bungalow in East Atlanta Village. Original character with modern upgrades including a new kitchen, updated electrical and plumbing, and a landscaped backyard with fire pit.",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop"],
    agent: { name: "Jessica Taylor", phone: "(213) 555-0106", email: "jessica@aurarealty.com", photo: "" }
  },
  {
    id: 23,
    title: "Resort-Style Condo",
    price: 510000,
    address: "300 S Pointe Dr #1205",
    city: "Miami Beach",
    state: "FL",
    zip: "33139",
    lat: 25.7637,
    lng: -80.1340,
    beds: 2,
    baths: 2,
    sqft: 1400,
    type: "Condo",
    yearBuilt: 2021,
    status: "For Sale",
    featured: false,
    description: "Resort-style living at South Pointe. Ocean-view unit with balcony, impact windows, and designer finishes. Building amenities include beach service, two pools, fitness center, spa, and valet parking.",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop"],
    agent: { name: "Emily Rodriguez", phone: "(203) 555-0103", email: "emily@aurarealty.com", photo: "" }
  },
  {
    id: 24,
    title: "Vineyard Country Estate",
    price: 2800000,
    address: "1 Vineyard Hill Rd",
    city: "Napa",
    state: "CA",
    zip: "94558",
    lat: 38.2975,
    lng: -122.2869,
    beds: 5,
    baths: 5,
    sqft: 5000,
    type: "House",
    yearBuilt: 2019,
    status: "For Sale",
    featured: true,
    description: "Breathtaking estate surrounded by 10 acres of working vineyard. Stone and timber construction, wine cave, tasting room, infinity pool, and guest cottage. The ultimate Napa Valley lifestyle property.",
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop", "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop"],
    agent: { name: "Michael Chen", phone: "(305) 555-0102", email: "michael@aurarealty.com", photo: "" }
  }
];

/**
 * Neighborhoods data for the Home page spotlight section
 */
const NEIGHBORHOODS = [
  { name: "Miami Beach", city: "Miami", state: "FL", properties: 156, image: "https://images.unsplash.com/photo-1533106497176-45ae19e68ba2?w=600&h=400&fit=crop" },
  { name: "Beverly Hills", city: "Los Angeles", state: "CA", properties: 89, image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop" },
  { name: "Upper West Side", city: "New York", state: "NY", properties: 234, image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=600&h=400&fit=crop" },
  { name: "Back Bay", city: "Boston", state: "MA", properties: 67, image: "https://images.unsplash.com/photo-1501979376754-1d81b6aa8a97?w=600&h=400&fit=crop" },
  { name: "Napa Valley", city: "Napa", state: "CA", properties: 42, image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=600&h=400&fit=crop" },
  { name: "Capitol Hill", city: "Washington", state: "DC", properties: 113, image: "https://images.unsplash.com/photo-1501466044931-62695aada8e9?w=600&h=400&fit=crop" }
];

/**
 * Testimonials data for the Home page
 */
const TESTIMONIALS = [
  {
    name: "Jennifer & Mark Thompson",
    location: "Miami, FL",
    rating: 5,
    text: "Aura Realty made our dream of owning a waterfront home a reality. Sarah was incredibly knowledgeable about the market and guided us through every step. We couldn't be happier with our new home!",
    photo: ""
  },
  {
    name: "Robert Kim",
    location: "New York, NY",
    rating: 5,
    text: "As a first-time buyer in NYC, the process seemed overwhelming. David at Aura Realty was patient, professional, and found me the perfect apartment within my budget. Highly recommend!",
    photo: ""
  },
  {
    name: "Amanda & Carlos Rivera",
    location: "Austin, TX",
    rating: 5,
    text: "We relocated from California and needed to find a home quickly. The Aura Realty team went above and beyond, showing us dozens of homes and negotiating an amazing deal. Five stars!",
    photo: ""
  }
];

/**
 * Team members data for the About page
 */
const TEAM_MEMBERS = [
  {
    name: "Sarah Mitchell",
    role: "Founder & CEO",
    bio: "With over 20 years of experience in luxury real estate, Sarah founded Aura Realty to redefine the home buying experience. Her vision combines cutting-edge technology with personalized white-glove service.",
    phone: "(305) 555-0101",
    email: "sarah@aurarealty.com",
    photo: ""
  },
  {
    name: "Michael Chen",
    role: "Senior Agent",
    bio: "Michael specializes in investment properties and has helped clients build portfolios worth over $50M. His analytical approach and market expertise make him a trusted advisor for savvy investors.",
    phone: "(305) 555-0102",
    email: "michael@aurarealty.com",
    photo: ""
  },
  {
    name: "Emily Rodriguez",
    role: "Luxury Specialist",
    bio: "Emily brings a refined eye for design and an extensive network to every transaction. She specializes in high-end residential properties and has a track record of record-breaking sales.",
    phone: "(203) 555-0103",
    email: "emily@aurarealty.com",
    photo: ""
  },
  {
    name: "David Park",
    role: "First-Time Buyer Expert",
    bio: "David is passionate about helping first-time buyers navigate the market with confidence. His patient, educational approach has earned him a 100% client satisfaction rating.",
    phone: "(212) 555-0104",
    email: "david@aurarealty.com",
    photo: ""
  },
  {
    name: "Jessica Taylor",
    role: "Marketing Director",
    bio: "Jessica leads Aura Realty's innovative marketing strategies, leveraging digital platforms and data analytics to ensure every listing reaches the right audience at the right time.",
    phone: "(213) 555-0106",
    email: "jessica@aurarealty.com",
    photo: ""
  },
  {
    name: "James Wilson",
    role: "Property Manager",
    bio: "James oversees Aura Realty's property management division, ensuring every rental property is maintained to the highest standards while maximizing returns for property owners.",
    phone: "(305) 555-0107",
    email: "james@aurarealty.com",
    photo: ""
  }
];

/**
 * Services data for the Services page
 */
const SERVICES = [
  {
    icon: "fa-home",
    title: "Residential Sales",
    description: "From starter homes to luxury estates, our experienced agents guide you through every step of buying or selling your home. We leverage market data and our extensive network to ensure the best outcomes.",
    features: ["Comparative market analysis", "Professional staging consultation", "Strategic pricing", "Negotiation expertise"]
  },
  {
    icon: "fa-building",
    title: "Commercial Real Estate",
    description: "Our commercial division handles office spaces, retail locations, and industrial properties. We understand the unique needs of business clients and deliver tailored solutions.",
    features: ["Lease negotiations", "Investment analysis", "Property valuations", "Tenant placement"]
  },
  {
    icon: "fa-key",
    title: "Property Management",
    description: "Let us handle the day-to-day operations of your rental properties. From tenant screening to maintenance coordination, we protect your investment and maximize your returns.",
    features: ["Tenant screening", "Rent collection", "Maintenance coordination", "Financial reporting"]
  },
  {
    icon: "fa-chart-line",
    title: "Investment Advisory",
    description: "Build wealth through strategic real estate investments. Our advisors analyze market trends, identify opportunities, and help you build a diversified property portfolio.",
    features: ["Market analysis", "ROI projections", "Portfolio diversification", "1031 exchanges"]
  },
  {
    icon: "fa-handshake",
    title: "Relocation Services",
    description: "Moving to a new city? Our relocation team provides comprehensive support including area orientation, school information, and personalized home search to make your transition seamless.",
    features: ["Area orientation tours", "School district research", "Temporary housing", "Community integration"]
  },
  {
    icon: "fa-gavel",
    title: "Luxury Auctions",
    description: "Our auction platform connects exceptional properties with qualified buyers worldwide. A transparent, efficient process that can achieve premium prices in a defined timeframe.",
    features: ["Global buyer network", "Professional marketing", "Transparent bidding", "Accelerated timelines"]
  }
];
